[hostname]
ssh_only = false
format =  "@[$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true
