#!/usr/bin/env zsh
set -ue

cd "$(tmux showenv "$(tmux display -p "TMUX_PWD_#D")" | cut -d= -f2-)"

short_pwd() {
  pwd | sed "s#^$HOME#~#; s#\([a-zA-Z]\)[a-zA-Z]*[^/]*/#\1/#g"
}

git_status() {
  local unstaged="$(git diff-files | wc -l)"
  local staged="$(git diff-index --cached HEAD | wc -l)"
  if [[ "$unstaged" -gt 0 ]]; then
    printf " #[fg=colour3]%d waiting " "$unstaged"
  fi
  if [[ "$staged" -gt 0 ]]; then
    printf " #[fg=colour1]%d staged " "$staged"
  fi
}

git_since() {
  local seconds="$(git since)"
  if [[ "$seconds" -gt 3600 ]]; then
    printf " #[fg=colour9]$((seconds / 3600))h$((seconds % 3600 / 60))m "
  elif [[ "$seconds" -gt 60 ]]; then
    printf " #[fg=colour2]$((seconds / 60))m "
  else
    printf " #[fg=colour2]<1m "
  fi
}

git_branch() {
  printf " #[fg=colour7]$(git rev-parse --abbrev-ref HEAD) "
}

git_pwd() {
  local color
  if git trusted; then
    color="colour9"
  else
    color="colour4"
  fi
  printf " #[fg=$color]%s" "$(short_pwd)"
}

battery() {
	printf " #[fg=colour2]%s" "$(acpi -b | sed -r 's/^.*, ([0-9]+)%.*/\1/')%"

	if acpi -b | grep Charging &> /dev/null; then
		printf " \u26a1"
	fi
}

date_f() {
	printf " #[fg=colour5]%s" "$(date +"%d %b %H:%M")"
}

if git root &> /dev/null; then
	date_f
	battery
  git_status
  git_since
  git_branch
  git_pwd
else
	date_f
	battery
	printf " #[fg=colour4]%s" "$(short_pwd)"
fi
